name: Build Action

on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Publish SuperiorSkyblock-zMenu
    uses: GroupeZ-dev/actions/.github/workflows/build.yml@main
    with:
      project-name: "SuperiorSkyblock-zMenu"
      publish: false
      project-to-publish: "API:publish"
      discord-avatar-url: "https://bg-software.com/imgs/website-icon.png"
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      MAVEN_USERNAME: ""
      MAVEN_PASSWORD: ""